set -g status on
set -g allow-passthrough on
set -g default-command "__SHELL_WRAPPER__"
set -ga update-environment " GHOSTTY_TMUX_ATTACH_ACTIVE GHOSTTY_USER_SHELL"
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-capture-pane-contents 'on'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'
